version: '3.9'

networks:
  micro_network:
    external:
      name: micro_network

services:
  backend:
    container_name: backend-container
    build: ./backEnd
    ports:
      - "5000:5000"
    networks:
      - micro_network 
    restart: always
    
  frontend:
    container_name: frontend-container
    build: ./frontEnd
    ports:
      - "4000:4000"
    networks:
      - micro_network    
    restart: always

  reporting:
    container_name: reporting-container
    build: ./reporting
    ports:
      - "5003:5003"
    networks:
      - micro_network    
    restart: always

